### ISSUE TITLE
use_worldguard inneficient

### ISSUE THREAD

**Issue by sholan** [instance01/skins#2]
Hi !

Just installed skins on my server which doesn't use worldguard.
I set use_worldguard to false but still got errors at launch.

After looking at the code, noticed that (in Main.java) com.sk89q.worldguard.bukkit.WorldGuardPlugin is allways imported no matter the value of use_worldguard.

Can you plan on resolving this issue ?

skins version used : v1.8.2

Regards,

sholan

**Comment by instance01** [comment]
Thank you for letting me know!

Included here: http://dev.bukkit.org/bukkit-plugins/skin-statue-builder/files/36-skin-statue-builder-v1-8-3/

**Comment by sholan** [comment]
Nice reactivity, i'll check it tomorrow, letting you know

**Comment by sholan** [comment]
It works perfectly without worldguard, thanks !
